name: npm publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '2.1.0-manual'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  publish-and-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: Sync version
        run: |
          if [ "${{ github.event.inputs.version }}" != "" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${{ github.ref_name }}"
          fi
          echo "VERSION_TO_PUBLISH=$VERSION" >> $GITHUB_ENV
          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            npm version $VERSION --no-git-tag-version
          else
            exit 1
          fi

      - name: Publish to NPM
        run: |
          if [[ "$VERSION_TO_PUBLISH" == *"-"* ]]; then
            npm publish --access public --provenance --tag next
          else
            npm publish --access public --provenance
          fi
